module.exports = {
  nodes: [
    {
      //id: 1,
      label: 'The first room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'blue',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 2,
      label: 'The second room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'An elaborately decorated room.',
      description:
        'This room is festooned with gaudy decorations. Nearly every surface is covered with some kind of intricate pattern.',
      group: 'tutorial',
      color: 'blue',
      tooltips: {
        decorations: 'Sometimes there will be hidden information in these descriptions',
        pattern:
          'One repeated motif is a series of colors arranged in a circle, each color signifying a different region of the landscape.',
      },
      neighbors: [],
    },
    {
      //id: 3,
      label: 'The third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'contemporary',
      color: 'green',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'medieval',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The fantasy room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'fantasy',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other fantasy room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'fantasy',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A fantasy room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'fantasy',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'medieval',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 1,
      label: 'The first room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'blue',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 2,
      label: 'The second room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'An elaborately decorated room.',
      description:
        'This room is festooned with gaudy decorations. Nearly every surface is covered with some kind of intricate pattern.',
      group: 'tutorial',
      color: 'blue',
      tooltips: {
        decorations: 'Sometimes there will be hidden information in these descriptions',
        pattern:
          'One repeated motif is a series of colors arranged in a circle, each color signifying a different region of the landscape.',
      },
      neighbors: [],
    },
    {
      //id: 3,
      label: 'The third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'contemporary',
      color: 'green',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'medieval',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The fantasy room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'fantasy',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other fantasy room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'fantasy',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A fantasy room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'fantasy',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'medieval',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'sci-fi',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'void',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
    {
      //id: 4,
      label: 'The other third room',
      username: 'micha',
      penName: 'Michanations',
      summary: 'A simple room with information placards on one wall.',
      description:
        'This room is completely unadorned, save for a gigantic series of information diagrams on the east wall. There is a single door leading out of the room.',
      group: 'tutorial',
      color: 'purple',
      tooltips: {
        information: 'You can hover over words like this to get more information',
        door: 'This door leads to the next room. Hover over that room in the map view to see what might be inside.',
      },
      neighbors: [],
    },
    {
      //id: 5,
      label: 'A room too far',
      username: 'micha',
      penName: 'Michanations',
      summary: 'This room should not be visible from the first room',
      description: 'This room is only theoretical.',
      group: 'horror',
      color: 'black',
      tooltips: {
        theoretical: 'How are you even reading this?',
      },
      neighbors: [],
    },
  ],
};
